import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import { useAppContext } from '../context/AppContext'
import { TaskListItem } from '../components/TaskkListItem'

const Home: NextPage = () => {
  const { state, dispatch } = useAppContext();
  const { tasks } = state;


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {tasks.map((task) => (
          <TaskListItem task={task} key={task.id} />
        ))}
        <button onClick={() => dispatch({ type: "create_task", value: { title: 'new task' } })}>
          Add task
        </button>

      </main>
    </div>
  )
}

export default Home
