import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from 'react'
import { useAppContext } from '../context/AppContext'
import { TaskListItem } from '../components/TaskkListItem'
import router from 'next/router'

const Home: NextPage = () => {
  const { state, dispatch } = useAppContext();
  const { tasks } = state;


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {tasks.map((task) => (
          <TaskListItem task={task} key={task.id} />
        ))}

        <div className="absolute right-4 bottom-4 ">
          <button className="bg-blue-800 text-gray-50 pb-2 px-3 rounded-full text-4xl shadow-lg hover:shadow hover:bg-blue-900 hover:text-white transition-all" onClick={() => { router.push('/create') }}>
            +
          </button>
        </div>

      </main>
    </>
  )
}

export default Home
